# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import twopc_pb2 as twopc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in twopc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPhaseCommitServiceStub(object):
    """============================================================
    Inter-node 2PC RPCs (coordinator <-> participants)
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoteRequest = channel.unary_unary(
                '/twopc.TwoPhaseCommitService/VoteRequest',
                request_serializer=twopc__pb2.VoteRequestMessage.SerializeToString,
                response_deserializer=twopc__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GlobalDecision = channel.unary_unary(
                '/twopc.TwoPhaseCommitService/GlobalDecision',
                request_serializer=twopc__pb2.DecisionMessage.SerializeToString,
                response_deserializer=twopc__pb2.DecisionAck.FromString,
                _registered_method=True)


class TwoPhaseCommitServiceServicer(object):
    """============================================================
    Inter-node 2PC RPCs (coordinator <-> participants)
    ============================================================

    """

    def VoteRequest(self, request, context):
        """Q1: Voting Phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalDecision(self, request, context):
        """Q2: Decision Phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseCommitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=twopc__pb2.VoteRequestMessage.FromString,
                    response_serializer=twopc__pb2.VoteResponse.SerializeToString,
            ),
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=twopc__pb2.DecisionMessage.FromString,
                    response_serializer=twopc__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPhaseCommitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPhaseCommitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseCommitService(object):
    """============================================================
    Inter-node 2PC RPCs (coordinator <-> participants)
    ============================================================

    """

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseCommitService/VoteRequest',
            twopc__pb2.VoteRequestMessage.SerializeToString,
            twopc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseCommitService/GlobalDecision',
            twopc__pb2.DecisionMessage.SerializeToString,
            twopc__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IntraNodePhaseServiceStub(object):
    """============================================================
    Intra-node RPCs (voting phase <-> decision phase on same node)
    Assignment requires gRPC between phases even within one container.
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyDecision = channel.unary_unary(
                '/twopc.IntraNodePhaseService/NotifyDecision',
                request_serializer=twopc__pb2.IntraDecisionNotification.SerializeToString,
                response_deserializer=twopc__pb2.IntraDecisionAck.FromString,
                _registered_method=True)
        self.ReportVote = channel.unary_unary(
                '/twopc.IntraNodePhaseService/ReportVote',
                request_serializer=twopc__pb2.IntraVoteReport.SerializeToString,
                response_deserializer=twopc__pb2.IntraVoteAck.FromString,
                _registered_method=True)


class IntraNodePhaseServiceServicer(object):
    """============================================================
    Intra-node RPCs (voting phase <-> decision phase on same node)
    Assignment requires gRPC between phases even within one container.
    ============================================================

    """

    def NotifyDecision(self, request, context):
        """Decision phase notifies voting phase of the final outcome
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportVote(self, request, context):
        """Voting phase reports its vote to the decision phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntraNodePhaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyDecision,
                    request_deserializer=twopc__pb2.IntraDecisionNotification.FromString,
                    response_serializer=twopc__pb2.IntraDecisionAck.SerializeToString,
            ),
            'ReportVote': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportVote,
                    request_deserializer=twopc__pb2.IntraVoteReport.FromString,
                    response_serializer=twopc__pb2.IntraVoteAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.IntraNodePhaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.IntraNodePhaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntraNodePhaseService(object):
    """============================================================
    Intra-node RPCs (voting phase <-> decision phase on same node)
    Assignment requires gRPC between phases even within one container.
    ============================================================

    """

    @staticmethod
    def NotifyDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.IntraNodePhaseService/NotifyDecision',
            twopc__pb2.IntraDecisionNotification.SerializeToString,
            twopc__pb2.IntraDecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.IntraNodePhaseService/ReportVote',
            twopc__pb2.IntraVoteReport.SerializeToString,
            twopc__pb2.IntraVoteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
