# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"8\n\x0eLocationUpdate\x12\x10\n\x08user_jwt\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\"t\n\x12VoteRequestMessage\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x05\x12.\n\x0fproposed_update\x18\x03 \x01(\x0b\x32\x15.twopc.LocationUpdate\"c\n\x0cVoteResponse\x12\x16\n\x0eparticipant_id\x18\x01 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x05\x12\x13\n\x0bvote_commit\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\x7f\n\x0f\x44\x65\x63isionMessage\x12\x16\n\x0e\x63oordinator_id\x18\x01 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x05\x12\x15\n\rglobal_commit\x18\x03 \x01(\x08\x12%\n\x06update\x18\x04 \x01(\x0b\x32\x15.twopc.LocationUpdate\"N\n\x0b\x44\x65\x63isionAck\x12\x16\n\x0eparticipant_id\x18\x01 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x61pplied\x18\x03 \x01(\x08\"J\n\x19IntraDecisionNotification\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x15\n\rglobal_commit\x18\x02 \x01(\x08\"(\n\x10IntraDecisionAck\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\">\n\x0fIntraVoteReport\x12\x16\n\x0etransaction_id\x18\x01 \x01(\x05\x12\x13\n\x0bvote_commit\x18\x02 \x01(\x08\"$\n\x0cIntraVoteAck\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\x94\x01\n\x15TwoPhaseCommitService\x12=\n\x0bVoteRequest\x12\x19.twopc.VoteRequestMessage\x1a\x13.twopc.VoteResponse\x12<\n\x0eGlobalDecision\x12\x16.twopc.DecisionMessage\x1a\x12.twopc.DecisionAck2\x9f\x01\n\x15IntraNodePhaseService\x12K\n\x0eNotifyDecision\x12 .twopc.IntraDecisionNotification\x1a\x17.twopc.IntraDecisionAck\x12\x39\n\nReportVote\x12\x16.twopc.IntraVoteReport\x1a\x13.twopc.IntraVoteAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCATIONUPDATE']._serialized_start=22
  _globals['_LOCATIONUPDATE']._serialized_end=78
  _globals['_VOTEREQUESTMESSAGE']._serialized_start=80
  _globals['_VOTEREQUESTMESSAGE']._serialized_end=196
  _globals['_VOTERESPONSE']._serialized_start=198
  _globals['_VOTERESPONSE']._serialized_end=297
  _globals['_DECISIONMESSAGE']._serialized_start=299
  _globals['_DECISIONMESSAGE']._serialized_end=426
  _globals['_DECISIONACK']._serialized_start=428
  _globals['_DECISIONACK']._serialized_end=506
  _globals['_INTRADECISIONNOTIFICATION']._serialized_start=508
  _globals['_INTRADECISIONNOTIFICATION']._serialized_end=582
  _globals['_INTRADECISIONACK']._serialized_start=584
  _globals['_INTRADECISIONACK']._serialized_end=624
  _globals['_INTRAVOTEREPORT']._serialized_start=626
  _globals['_INTRAVOTEREPORT']._serialized_end=688
  _globals['_INTRAVOTEACK']._serialized_start=690
  _globals['_INTRAVOTEACK']._serialized_end=726
  _globals['_TWOPHASECOMMITSERVICE']._serialized_start=729
  _globals['_TWOPHASECOMMITSERVICE']._serialized_end=877
  _globals['_INTRANODEPHASESERVICE']._serialized_start=880
  _globals['_INTRANODEPHASESERVICE']._serialized_end=1039
# @@protoc_insertion_point(module_scope)
